#!/usr/bin/env node
/**
 * Generates README.md from the app's own data (version, workout templates,
 * machines) so the README never drifts from the code.
 *
 * Usage: node scripts/gen-readme.mjs
 */

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { APP_VERSION, REST_TARGETS } from '../js/config.js';
import { DEFAULT_DATA } from '../js/data-defaults.js';

const LIVE_URL = 'https://adamborecki.github.io/gym/';
const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

const { machines, templates } = DEFAULT_DATA;
const name = (id) => machines[id]?.name || id;
const reps = (m) => (m.repRange?.max > 0 ? `${m.repRange.min}–${m.repRange.max}` : '—');

function templateSection(t) {
  const rows = t.blocks
    .filter(b => b.id !== 'warmup')
    .map(b => {
      const joiner = b.completion === 'any' ? ' **or** ' : ', ';
      const note = b.completion === 'any' ? ' _(any one completes the block)_' : '';
      return `| ${b.name} | ${b.suggestions.map(name).join(joiner)}${note} |`;
    });
  return [`### ${t.name}`, '', '| Block | Machines |', '|---|---|', ...rows, ''].join('\n');
}

const CATEGORY_ORDER = ['push', 'pull', 'legs', 'core', 'cardio'];
const machineRows = Object.values(machines)
  .sort((a, b) => CATEGORY_ORDER.indexOf(a.category) - CATEGORY_ORDER.indexOf(b.category))
  .map(m => `| ${m.name} | ${m.category} | ${m.type} | ${reps(m)} |`);

const readme = `<!-- Generated by scripts/gen-readme.mjs — edit that script, not this file. -->

# Gym

A single-focus gym app that replaces four separate apps with one: workout plan, set logger, rest timer, and stats.

## ▶ Try it live

**[${LIVE_URL}](${LIVE_URL})**

Open it on your phone and use **Add to Home Screen** for a full-screen, app-like experience. It deploys automatically from \`main\` via GitHub Pages.

Current version: \`${APP_VERSION}\`

## Features

- **Guided sessions**: pick Push / Pull / Legs / Bonus, then choose a *count-down* (leave-by time) or *count-up* timer
- **Set logging built around real gym flow**: adjust the weight, do the set, tap **Set Done** (the rest timer starts right away), then enter reps and RIR while you rest
- **Rest timer** with Normal and Hurry targets (compound ${REST_TARGETS.compound.normal}s / ${REST_TARGETS.compound.hurry}s, isolation ${REST_TARGETS.isolation.normal}s / ${REST_TARGETS.isolation.hurry}s) and a soft audio swell plus vibration when rest is up
- **Per-machine coaching**: setup tips, form tips, a sticky mantra with tempo cues, and optional read-aloud
- **Saved setup**: seat, range, handle position, and grip are remembered per machine and recorded with each set
- **Progress nudges**: target RIR per set, rep ranges, "weight up next time?" prompts, and last session's plan shown before your first set
- **Fix mistakes**: tap ✎ on any logged set to edit or delete it
- **Stats**: session timeline (time per machine, prep time, estimated warm-up), a workout calendar heatmap, and weekly sets and bike charts
- **Private by design**: all data stays in your browser's localStorage; export a JSON backup any time from Settings

## Workouts

${Object.values(templates).map(templateSection).join('\n')}
Every workout also starts with a warm-up (stretch and bike) and ends with an **Other** block where you can add any machine or create a custom one.

## Machines

| Machine | Category | Type | Rep range |
|---|---|---|---|
${machineRows.join('\n')}

## Your data

Everything is stored locally in your browser (\`localStorage\`), with no account and no server. Updating the app keeps your history: built-in content (tips, templates) refreshes on load, while your sessions, saved setups, and preferences are preserved. Data is tied to the site address and browser, so use **Settings → Download JSON backup** before switching phones or clearing browser data.

## Run locally

\`\`\`sh
python3 server.py   # http://localhost:8080 (no-cache headers so phones always get fresh files)
\`\`\`

No build step: plain HTML, CSS, and vanilla JS modules.

## Project structure

| Path | What |
|---|---|
| \`index.html\` | All views (single page) |
| \`css/app.css\` | Mobile-first styles; light and dark via \`prefers-color-scheme\` |
| \`js/app.js\` | Entry point, event wiring, data migration on load |
| \`js/workout.js\` | Workout view, machine view, set logger |
| \`js/session.js\` | Session lifecycle, event tracking, summary and timeline |
| \`js/timer.js\` | Rest timer and audio alert |
| \`js/analytics.js\` | Heatmap and weekly charts |
| \`js/data-defaults.js\` | Machines, tips, and workout templates |
| \`js/config.js\` | Version, rest targets, seed weights |

## Contributing

- Bump \`APP_VERSION\` in \`js/config.js\` on every change (\`vYYYY.MM.DDx\`)
- Regenerate this README after changing machines, templates, or the version: \`node scripts/gen-readme.mjs\`

## License

See [LICENSE](LICENSE).
`;

writeFileSync(join(ROOT, 'README.md'), readme);
console.log(`README.md generated (${APP_VERSION})`);
